config/routes.rb
MyVeryFirstRailsApp::Application.routes.draw do

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :stories, only: [:show, :new, :create] do
    get 'change', on: :member
    resources :comments, only: [:new, :create]
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/sort_by_name', to: 'static_pages#sort_by_name'
  match '/sort_by_state', to: 'static_pages#sort_by_state'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :descr

  belongs_to :story

  validates_presence_of :descr, on: :create
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :descr, :responsible

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates_presence_of :descr, on: :create
  validates_presence_of :responsible, on: :create

  state_machine :state, initial: :new do

    event :start do
      transition new: :started
    end

    event :finish do
      transition started: :finished
    end

    event :deliver do
      transition finished: :delivered
    end

    event :accept do
      transition delivered: :accepted
    end

    event :reject do
      transition delivered: :rejected
    end

    event :restart do
      transition rejected: :started
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  has_secure_password

  has_many :stories, dependent: :destroy

  before_save { |user| user.email = email.downcase }

  validates_presence_of :name, on: :create
  validates_uniqueness_of :name, on: :create
  validates_presence_of :email, on: :create
  validates_uniqueness_of :email, on: :create
  validates_presence_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @story = current_user.stories.find(params[:story_id])
    @comment = Comment.new
  end
  
  def create
    @story = current_user.stories.find(params[:story_id])
    @comment = @story.comments.build(params[:comment])
    if @comment.save
      redirect_to story_path(@story), notice: 'Comment added!'
    else
      @feed_items = @story.comments
      render 'stories/show'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path, :notice => "Logged in!"
    else
      flash.now[:error] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @feed_items = current_user.stories
    end
  end

  def sort_by_name
    @feed_items = current_user.stories.find(:all, order: 'responsible')
    render 'home'
  end

  def sort_by_state
    @feed_items = current_user.stories.find(:all, order: 'state')
    render 'home'
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def show
    @story = current_user.stories.find(params[:id])
    @comment = Comment.new
    @feed_items = @story.comments
  end

  def new
    @story = Story.new
    @users = construct_users
  end

  def create
    @story = current_user.stories.build(params[:story])
    if @story.save
      redirect_to root_path, notice: "Story created!"
    else
      @users = construct_users
      render "new"
    end
  end

  def construct_users
    users = []
    User.all.each do |user|
      users << user.name
    end
  end

  def change
    @story = current_user.stories.find(params[:id])
    case params[:do]
      when 'start'
        @story.start!
      when 'finish'
        @story.finish!
      when 'deliver'
        @story.deliver!
      when 'accept'
        @story.accept!
      when 'reject'
        @story.reject!
      when 'restart'
        @story.restart!
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to root_path, notice: "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.haml
.row
  .span4.offset4
    %h1 New comment
    = simple_form_for ([@story, @comment]) do |f|
      = f.input :descr, label: 'Comment'
      = f.button :submit, 'Comment'

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        %ul.nav.pull-right
          %li
            = link_to "Home", root_path
          - if signed_in?
            %li
              = link_to "Sign out", signout_path, method: "delete"
          - else
            %li
              = link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/ [if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyVeryFirstRailsApp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = debug(params) if Rails.env.development?

app/views/shared/_comment_feed.html.haml
- if @feed_items.any?
  %ol.feed
    = render partial: 'shared/comment_feed_item', collection: @feed_items
= simple_form_for ([@story, @comment]) do |f|
  = f.input :descr, label: 'Comment'
  = f.button :submit, 'Comment'

app/views/shared/_comment_feed_item.html.haml
%li
  %span.content
    = comment_feed_item.descr

app/views/static_pages/_story_feed.html.haml
- if @feed_items.any?
  %ol.feed
    = render partial: 'story_feed_item', collection: @feed_items

app/views/static_pages/_story_feed_item.html.haml
%li
  Responsible:
  = story_feed_item.responsible
  %span.content
    %h4= link_to story_feed_item.descr, story_feed_item
  - case story_feed_item.state
    - when 'new'
      = link_to 'start', change_story_path(story_feed_item, do: 'start'), class: 'btn btn-mini'
    - when 'started'
      = link_to 'finish', change_story_path(story_feed_item, do: 'finish'), class: 'btn btn-mini btn-primary'
    - when 'finished'
      = link_to 'deliver', change_story_path(story_feed_item, do: 'deliver'), class: 'btn btn-mini btn-warning'
    - when 'delivered'
      = link_to 'accept', change_story_path(story_feed_item, do: 'accept'), class: 'btn btn-mini btn-success'
      = link_to 'reject', change_story_path(story_feed_item, do: 'reject'), class: 'btn btn-mini btn-danger'
    - when 'rejected'
      = link_to 'restart', change_story_path(story_feed_item, do: 'restart'), class: 'btn btn-mini btn-primary'
  = link_to 'comment', new_story_comment_path(story_feed_item), class: 'btn btn-mini'

app/views/static_pages/home.html.haml
- if signed_in?
  .row
    .span4.offset4
      = link_to "New Story", new_story_path, class: "btn btn-large btn-primary"
      = link_to "By name", sort_by_name_path, class: "btn btn-large"
      = link_to "By state", sort_by_state_path, class: "btn btn-large"
      = render 'story_feed'
- else
  .center.hero-unit
    %h1 Welcome!
    %h2 This is my very first rails app
    = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"

app/views/stories/new.html.haml
.row
  .span4.offset4
    %h1 New Story
    = simple_form_for @story do |f|
      = f.input :responsible, collection: @users, required: 'true'
      = f.input :descr, required: 'true', label: 'Description'
      = f.button :submit, 'Create'

app/views/stories/show.html.haml
.row
  .span4.offset5
    Responsible:
    = @story.responsible
    %h4= @story.descr
    = render 'shared/comment_feed'

app/views/users/new.html.haml
.row
  .span4.offset4
    %h1 Sign up
    = simple_form_for @user do |f|
      = f.input :name, required: 'true'
      = f.input :email, required: 'true'
      = f.input :password
      = f.input :password_confirmation, required: 'true'
      = f.button :submit, 'Sign up!'